services:
  app:
    container_name: inventory-management-system
    depends_on:
      app_mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      env_file: ".env"
    ports:
      - ${EXTERNAL_APP_PORT}:${INTERNAL_APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm run start:dev"
    networks:
      - nestjs_app_network

  app_mysql:
    image: mysql:8.0.39
    container_name: app_mysql_container
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory-management-system
    networks:
      - nestjs_app_network
    volumes:
      - root_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=root"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5

  app_phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: app_phpmyadmin_container
    restart: unless-stopped
    depends_on:
      app_mysql:
        condition: service_healthy
    ports:
      - "8844:80"
    environment:
      PMA_HOST: app_mysql
      PMA_PORT: 3306
      PMA_PASSWORD: root
    networks:
      - nestjs_app_network

volumes:
  root_mysql_data:
    driver: local
networks:
  nestjs_app_network:
    driver: bridge
