import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';
import { ApiProperty } from '@nestjs/swagger';

/**
 * The `Item` entity represents an item in the inventory management system.
 * It is used to store information about the item in the database.
 * @description This class defines the structure of the `items` table and maps it to the `Item` class.
 */
@Entity('items')
export class Item {
    /**
     * The unique identifier of the item.
     * This field is a UUID generated automatically.
     * @type {string}
     * @example 'd9b1e2ab-9f45-45b1-89b5-820f7243002b'
     */
    @PrimaryGeneratedColumn('uuid')
    @ApiProperty({
        description: 'The unique identifier of the item',
        example: 'd9b1e2ab-9f45-45b1-89b5-820f7243002b',
    })
    item_id: string;

    /**
     * The name of the item.
     * @type {string}
     * @example 'Laptop'
     */
    @Column({ length: 100 })
    @ApiProperty({
        description: 'The name of the item',
        example: 'Laptop',
    })
    name: string;

    /**
     * A brief description of the item.
     * This field is optional.
     * @type {string | null}
     * @example 'A powerful gaming laptop with high-end specs.'
     */
    @Column({ type: 'text', nullable: true })
    @ApiProperty({
        description: 'A brief description of the item',
        example: 'A powerful gaming laptop with high-end specs.',
        required: false,
        nullable: true
    })
    description?: string;

    /**
     * The total quantity of the item available in stock.
     * @type {number}
     * @example 10
     */
    @Column({ type: 'int'})
    @ApiProperty({
        description: 'The total quantity of the item available in stock',
        example: 10,
    })
    quantity: number;

    /**
     * The number of items that are currently borrowed.
     * @type {number}
     * @default 0
     * @example 3
     */
    @Column({ type: 'int', default: 0 })
    @ApiProperty({
        description: 'The number of items that are currently borrowed',
        example: 3,
        default: 0,
    })
    borrowedQuantity: number;

    /**
     * The timestamp when the item was created.
     * This field is auto-generated by the database.
     * @type {Date}
     * @example '2025-01-10T12:34:56Z'
     */
    @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP' })
    @ApiProperty({
        description: 'The timestamp when the item was created. This field is auto-generated',
        example: '2025-01-10T12:34:56Z',
    })
    createdAt: Date;

    /**
     * The timestamp when the item was last updated.
     * This field is auto-generated and updated whenever the item is modified.
     * @type {Date}
     * @example '2025-01-10T12:34:56Z'
     */
    @Column({ type: 'timestamp', default: () => 'CURRENT_TIMESTAMP', onUpdate: 'CURRENT_TIMESTAMP' })
    @ApiProperty({
        description: 'The timestamp when the item was last updated. This field is auto-generated and updated',
        example: '2025-01-10T12:34:56Z',
    })
    updatedAt: Date;
}
